---
abstract: 'Simple virtual host implementation on Plack.'
author:
  - 'karupanerura <karupa@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.3, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-App-Vhost
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::App::Vhost:
    file: lib/Plack/App/Vhost.pm
    version: '0.01'
requires:
  List::Util: '1.28'
  Plack::Component: '0'
  Plack::Util::Accessor: '0'
  parent: '0'
  perl: '5.008005'
resources:
  bugtracker: https://git@github.com/karupanerura/Plack-App-Vhost/issues
  homepage: https://git@github.com/karupanerura/Plack-App-Vhost
  repository: git://git@github.com/karupanerura/Plack-App-Vhost.git
version: '0.01'
